const MAX_ROOMS = 10;
const MAX_PLAYERS = 10;

const ROOM_EXPIRY_MS = 10 * 60 * 1000;
const ROOM_CLEANUP_INTERVAL_MS = 60 * 60 * 1000;
const FINISHED_ROOM_CLEANUP_MS = 5 * 60 * 1000;
const LOBBY_DISCONNECT_GRACE_MS = 30 * 1000;
const ACTIVE_DISCONNECT_GRACE_MS = 60 * 1000;
const BOT_ACTION_DELAY_MIN_MS = 3 * 1000;
const BOT_ACTION_DELAY_MAX_MS = 7 * 1000;

module.exports = {
  MAX_ROOMS,
  MAX_PLAYERS,
  ROOM_EXPIRY_MS,
  ROOM_CLEANUP_INTERVAL_MS,
  FINISHED_ROOM_CLEANUP_MS,
  LOBBY_DISCONNECT_GRACE_MS,
  ACTIVE_DISCONNECT_GRACE_MS,
  BOT_ACTION_DELAY_MIN_MS,
  BOT_ACTION_DELAY_MAX_MS,
};
